# Generated by Django 5.2.7 on 2026-01-19 14:53

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('size', models.IntegerField(choices=[(1, 'Mini'), (2, 'Midi'), (3, 'Maxi')], default=3)),
                ('color', models.IntegerField(choices=[(1, 'Beige'), (2, 'White'), (3, 'Brown'), (4, 'Black'), (5, 'Red'), (6, 'Purple'), (7, 'Blue'), (8, 'Orange'), (9, 'Pink'), (10, 'Gold'), (11, 'Silver'), (12, 'Grey'), (13, 'Green'), (14, 'Yellow'), (15, 'Mixed')], default=15)),
                ('fabric', models.IntegerField(choices=[(1, 'Natural Leather'), (2, 'Vegan Leather'), (3, 'Cotton'), (4, 'Nylon'), (5, 'Vinyl'), (6, 'Jute'), (7, 'Canvas')], default=7)),
                ('price', models.PositiveIntegerField(verbose_name='price in zł')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_time', models.PositiveIntegerField()),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.bag')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='biblioteka.cart')),
            ],
            options={
                'unique_together': {('cart', 'bag')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('sent', 'Wysłane'), ('done', 'Zakończone'), ('canceled', 'Anulowane')], default='new', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_time', models.PositiveIntegerField()),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteka.bag')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='biblioteka.ordersummary')),
            ],
        ),
        migrations.CreateModel(
            name='User_acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('street_name', models.CharField(max_length=100)),
                ('home_nr', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Torebka',
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.user_acc'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.user_acc'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.user_acc'),
        ),
    ]
