# Generated by Django 5.2.7 on 2026-01-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_bag_cart_cartitem_order_ordersummary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='model',
            new_name='model_name',
        ),
    ]
