# Generated by Django 5.2.7 on 2025-12-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torebka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('size', models.IntegerField(choices=[(1, 'Mini'), (2, 'Midi'), (3, 'Maxi')], default=3)),
            ],
        ),
    ]
